addendum: Adapt: Go back to using WINDOWID instead of my own TERMID alternative, as there are (now) different meanings
For updating the terminal title, we need WINDOWID as that represents something that has a GUI window and therefore a title. A tmux session may have multiple windows consisting of potentially multiple panes, and each such shell would have its own TERMID, but there's just a single window for all of them.

diff --git a/lib/invocationNotification/extensions/addendum b/lib/invocationNotification/extensions/addendum
--- a/lib/invocationNotification/extensions/addendum
+++ b/lib/invocationNotification/extensions/addendum
@@ -3,8 +3,8 @@
 if ! type -t titleupdate >/dev/null; then
     echo >&2 'ERROR: titleupdate is not available.'
     return 3
-elif [ -z "$TERMID" ]; then
-    echo >&2 'ERROR: Cannot notify via titleupdate; TERMID not defined.'
+elif [ -z "$WINDOWID" ]; then
+    echo >&2 'ERROR: Cannot notify via titleupdate; WINDOWID not defined.'
     return 3
 fi
 
