Minor: Consistently use printUsage(), add newline before bottom hint

diff --git a/bin/countdown b/bin/countdown
--- a/bin/countdown
+++ b/bin/countdown
@@ -12,7 +12,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -126,12 +126,12 @@ do
 	--interval|-i)	shift; < <(timeWithAdjustmentToSeconds "$1") IFS=$'\t' read -r interval intervalAdjustment || exit 2; shift;;
 	--as)		shift; render="$1"; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
 if [ $# -ne 1 ]; then
-    printShortUsage "$0" >&2
+    printUsage "$0" >&2
     exit 2
 fi
 delay="$(timeToSeconds "$1")" || exit $?
@@ -189,7 +189,7 @@ case "$render" in
 		    duration=
 		    finalizer='updateDuration "${prefix:+ }$duration" ""'
 		    ;;
-    *)		    printf >&2 'Invalid render: %s\n' "$render"; echo >&2; printShortUsage "$0" >&2; exit 2;;
+    *)		    printf >&2 'Invalid render: %s\n' "$render"; echo >&2; printUsage "$0" >&2; exit 2;;
 esac
 
 SECONDS=0
diff --git a/bin/invocationMessage b/bin/invocationMessage
--- a/bin/invocationMessage
+++ b/bin/invocationMessage
@@ -23,7 +23,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 plural()
 {
@@ -162,7 +162,7 @@ abortSingleRenderer()
 {
     echo >&2 'ERROR: Only one of --inline[-stderr], --spinner[-stderr], or --sweep[-stderr] can be passed.'
     echo >&2
-    printShortUsage "$1" >&2
+    printUsage "$1" >&2
     exit 2
 }
 
@@ -206,7 +206,7 @@ do
 			clear="$1"
 			case "$clear" in
 			    success|failure|all)  ;;
-			    *)  { printf 'ERROR: Invalid value for --clear: %s\n' "$clear"; echo; printShortUsage "$0"; } >&2; exit 2;;
+			    *)  { printf 'ERROR: Invalid value for --clear: %s\n' "$clear"; echo; printUsage "$0"; } >&2; exit 2;;
 			esac
 			shift
 			;;
@@ -250,24 +250,24 @@ fi
 if [ -z "${message+t}" -a ${#commands[@]} -eq 0 ]; then
     echo 'ERROR: Must pass -m|--message MESSAGE and COMMAND(s).'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ -z "${message+t}" ]; then
     echo 'ERROR: Must pass -m|--message MESSAGE.'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ "$isInline" ] && [ "${#render[@]}" -gt 0 ]; then
     abortSingleRenderer "$0"
 elif [ -n "${timespan+t}" ] && [ ! "$isInline" ] && [ ${#render[@]} -eq 0 ]; then
     echo 'ERROR: --timespan can only be used in combination with one of --inline[-stderr], --spinner[-stderr], or --sweep[-stderr].'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ "$isRenderTimer" ] && [ ${#render[@]} -eq 0 ]; then
     echo 'ERROR: --render-timer can only be used in combination with --spinner[-stderr] or --sweep[-stderr].'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ ${#commands[@]} -eq 0 ]; then
     echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
diff --git a/bin/invocationNotification b/bin/invocationNotification
--- a/bin/invocationNotification
+++ b/bin/invocationNotification
@@ -25,7 +25,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 plural()
 {
@@ -166,18 +166,18 @@ timeToSeconds()
 singleTargetCheck()
 {
     if [ "$target" ]; then
-	echo >&2 "ERROR: There can be only one --to."
-	echo >&2
-	printShortUsage "$1" >&2
+	echo "ERROR: There can be only one --to."
+	echo
+	printUsage "$1"
 	exit 2
-    fi
+    fi >&2
 }
 
 abortSingleRenderer()
 {
     echo >&2 'ERROR: Only one of --inline[-stderr], --spinner[-stderr], or --sweep[-stderr] can be passed.'
     echo >&2
-    printShortUsage "$1" >&2
+    printUsage "$1" >&2
     exit 2
 }
 
@@ -260,7 +260,7 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--to|-o)	shift; singleTargetCheck "$0"; target="${1}Target"; if ! type -t "$target" >/dev/null; then printf 'ERROR: No such target: %s\n' "$1"; echo; printShortUsage "$0"; exit 2; fi >&2; shift;;
+	--to|-o)	shift; singleTargetCheck "$0"; target="${1}Target"; if ! type -t "$target" >/dev/null; then printf 'ERROR: No such target: %s\n' "$1"; echo; printUsage "$0"; exit 2; fi >&2; shift;;
 	--message|-m)	shift; message="$1"; shift;;
 	--success)	shift; successSigil="$1"; shift;;
 	--fail)		shift; failSigil="$1"; shift;;
@@ -268,7 +268,7 @@ do
 			clear="$1"
 			case "$clear" in
 			    success|failure|all)  ;;
-			    *)  { printf 'ERROR: Invalid value for --clear: %s\n' "$clear"; echo; printShortUsage "$0"; } >&2; exit 2;;
+			    *)  { printf 'ERROR: Invalid value for --clear: %s\n' "$clear"; echo; printUsage "$0"; } >&2; exit 2;;
 			esac
 			shift
 			;;
@@ -314,29 +314,29 @@ fi
 if [ -z "$target" -a -z "${message+t}" -a ${#commands[@]} -eq 0 ]; then
     echo 'ERROR: Must pass -o|--to overlay|title|command|notify and -m|--message MESSAGE and COMMAND(s).'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ -z "$target" ]; then
     echo 'ERROR: No --to target passed.'
     echo
-    printShortUsage "$1"
+    printUsage "$1"
     exit 2
 elif [ -z "${message+t}" ]; then
     echo 'ERROR: Must pass -m|--message MESSAGE.'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ "$isInline" ] && [ "${#render[@]}" -gt 0 ]; then
     abortSingleRenderer "$0"
 elif [ -n "${timespan+t}" ] && [ ! "$isInline" ] && [ ${#render[@]} -eq 0 ]; then
     echo 'ERROR: --timespan can only be used in combination with one of --inline[-stderr], --spinner[-stderr], or --sweep[-stderr].'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ "$isRenderTimer" ] && [ ${#render[@]} -eq 0 ]; then
     echo 'ERROR: --render-timer can only be used in combination with --spinner[-stderr] or --sweep[-stderr].'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ ${#commands[@]} -eq 0 ]; then
     echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
