Refactoring: Replace the duplicated inlined and one external invocation with lib/secondsToDurationSimple.sh
durationMessage somehow invoked my external secondsToDuration command, but the other scripts all have their own simple function inlined.
Let's extract this duplication and consistently use a library script for all. Even durationMessage doesn't need the (now enhanced, with actual rounding) functionality of the external script; a simple Bash implementation will do, and the small output customization can be achieved via an optional soleSecondFormat parameter.

diff --git a/bin/countdown b/bin/countdown
--- a/bin/countdown
+++ b/bin/countdown
@@ -1,6 +1,10 @@
 #!/bin/bash
 shopt -qs extglob
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
@@ -141,26 +145,6 @@ fi
 delay="$(timeToSeconds "$1")" || exit $?
 
 
-secondsToDuration()
-{
-    local seconds="${1:?}"; shift
-    local weeks=$((seconds / 604800))
-    seconds=$((seconds - 604800 * weeks))
-    local days=$((seconds / 86400))
-    seconds=$((seconds - 86400 * days))
-    local hours=$((seconds / 3600))
-    seconds=$((seconds - 3600 * hours))
-    local minutes=$((seconds / 60))
-    seconds=$((seconds - (60 * minutes)))
-
-    local renderedWeeks renderedDays renderedHours renderedMinutes renderedSeconds
-    [ $weeks -gt 0 ] && renderedWeeks="${weeks}w "
-    [ $days -gt 0 ] && renderedDays="${days}d "
-    [ $weeks -gt 0 -o $days -gt 0 -o $hours -gt 0 ] && printf -v renderedHours %02d: "$hours"
-    [ $weeks -gt 0 -o $days -gt 0 -o $hours -gt 0 -o $minutes -gt 0 ] && printf -v renderedMinutes %02d: "$minutes"
-    [ $weeks -gt 0 -o $days -gt 0 -o $hours -gt 0 -o $minutes -gt 0 ] && printf -v renderedSeconds %02d "$seconds" || renderedSeconds="$seconds"
-    printf '%s%s%s%s%s' "$renderedWeeks" "$renderedDays" "$renderedHours" "$renderedMinutes" "$renderedSeconds"
-}
 updateDuration()
 {
     local previousDuration="$1"; shift
@@ -202,7 +186,7 @@ do
     case "$render" in
 	dot)	    printf '.';;
 	ephemereal) previousDuration="$duration"
-		    duration="$(secondsToDuration "$((delay - SECONDS))")"
+		    duration="$("${projectDir}/lib/secondsToDurationSimple.sh"  "$((delay - SECONDS))")"
 		    updateDuration "$previousDuration" "$duration"
 		    ;;
 
diff --git a/bin/durationMessage b/bin/durationMessage
--- a/bin/durationMessage
+++ b/bin/durationMessage
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
@@ -223,7 +227,7 @@ expandSymbols()
     local message="$1"; shift
     message="${message//\%COUNT%/${UPDATE_COUNT}}"
     if [ "${message/\%DURATION%/}" != "$message" ]; then
-	message="${message//%DURATION%/$(secondsToDuration -- "$((NOW - START_EPOCH))")}"
+	message="${message//%DURATION%/$("${projectDir}/lib/secondsToDurationSimple.sh" "$((NOW - START_EPOCH))" '00:%02d')}"
     fi
     if [ "${message/\%TIMESTAMP%/}" != "$message" ]; then
 	message="${message//%TIMESTAMP%/$(date -d "@$NOW" "+$DURATION_MESSAGE_TIMESTAMP")}"
diff --git a/bin/invocationMessage b/bin/invocationMessage
--- a/bin/invocationMessage
+++ b/bin/invocationMessage
@@ -19,6 +19,10 @@ typeset -a spinner=("${BASH_REMATCH[@]:1}" '')
 IFS=, read -r -a sweeps <<<"$INVOCATIONMESSAGE_SWEEPS"
 sweeps=("${sweeps[@]:1}" "${sweeps[0]//?/}")   # We use the initial (sweep start) rendering only for determining the number of characters used by the sweep.
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
@@ -469,30 +473,10 @@ printDuration()
 	printMessage "$@"
     fi
 }
-secondsToDuration()
-{
-    local seconds="${1:?}"; shift
-    local weeks=$((seconds / 604800))
-    seconds=$((seconds - 604800 * weeks))
-    local days=$((seconds / 86400))
-    seconds=$((seconds - 86400 * days))
-    local hours=$((seconds / 3600))
-    seconds=$((seconds - 3600 * hours))
-    local minutes=$((seconds / 60))
-    seconds=$((seconds - (60 * minutes)))
-
-    local renderedWeeks renderedDays renderedHours renderedMinutes renderedSeconds
-    [ $weeks -gt 0 ] && renderedWeeks="${weeks}w "
-    [ $days -gt 0 ] && renderedDays="${days}d "
-    [ $weeks -gt 0 -o $days -gt 0 -o $hours -gt 0 ] && printf -v renderedHours %02d: "$hours"
-    [ $weeks -gt 0 -o $days -gt 0 -o $hours -gt 0 -o $minutes -gt 0 ] && printf -v renderedMinutes %02d: "$minutes"
-    [ $weeks -gt 0 -o $days -gt 0 -o $hours -gt 0 -o $minutes -gt 0 ] && printf -v renderedSeconds %02d "$seconds" || renderedSeconds="${seconds}s"
-    printf '%s%s%s%s%s' "$renderedWeeks" "$renderedDays" "$renderedHours" "$renderedMinutes" "$renderedSeconds"
-}
 renderedDuration=
 renderDuration()
 {
-    renderedDuration="$(secondsToDuration "$duration")"
+    renderedDuration="$("${projectDir}/lib/secondsToDurationSimple.sh" "$duration")"
 }
 renderCurrentDuration()
 {
