invocationNotification: Implement inline + render combination

diff --git a/bin/invocationNotification b/bin/invocationNotification
--- a/bin/invocationNotification
+++ b/bin/invocationNotification
@@ -10,7 +10,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-m|--message MESSAGE -o|--to overlay|title|command|notify [--success SIGIL] [--fail SIGIL] [-C|--clear success|failure|all] [-i|--inline|--spinner|--sweep|--inline-stderr|--spinner-stderr|--sweep-stderr [-t|--timespan TIMESPAN[SUFFIX]]] [-T|--initial-delay TIMESPAN[SUFFIX]] -c|--command COMMANDLINE [...]|[--] SIMPLECOMMAND'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-m|--message MESSAGE -o|--to overlay|title|command|notify [--success SIGIL] [--fail SIGIL] [-C|--clear success|failure|all] [-i|--inline|--spinner|--sweep|--inline-stderr|--spinner-stderr|--sweep-stderr|--inline-spinner-stderr|--inline-sweep-stderr [-t|--timespan TIMESPAN[SUFFIX]]] [-T|--initial-delay TIMESPAN[SUFFIX]] -c|--command COMMANDLINE [...]|[--] SIMPLECOMMAND'
 }
 printUsage()
 {
@@ -86,6 +86,14 @@ HELPDESCRIPTION
 			Rider-alike sweeping control after MESSAGE (to indicate
 			that COMMAND is still doing its job). The output itself
 			is discarded.
+    --inline-spinner-stderr
+			Lines printed to stdout are appended as with --inline,
+			but lines printed to stderr make a spinner after MESSAGE
+			/ the last line rotate like --spinner-stderr.
+    --inline-sweep-stderr
+			Lines printed to stdout are appended as with --inline,
+			but lines printed to stderr changes a sweeping control
+			after MESSAGE / the last line like --sweep-stderr.
     --timespan|-t TIMESPAN[SUFFIX]
 			Only append / spin / sweep a line every TIMESPAN instead
 			of every second. Use --timespan 0 to use every line.
@@ -204,6 +212,7 @@ failSigil=
 clear=
 isCaptureStdout=
 isInline=
+isInlineWithRender=
 typeset -a render=()
 unset timespan
 initialDelay=0
@@ -232,10 +241,14 @@ do
 			shift; [ ${#render[@]} -eq 0 ] || abortSingleRenderer "$0"; render=("${SPINNER[@]}"); isCaptureStdout=t;;
 	--spinner-stderr)
 			shift; [ ${#render[@]} -eq 0 ] || abortSingleRenderer "$0"; render=("${SPINNER[@]}");;
+	--inline-spinner-stderr)
+			shift; [ ${#render[@]} -eq 0 ] || abortSingleRenderer "$0"; render=("${SPINNER[@]}"); isCaptureStdout=t; isInlineWithRender=t;;
 	--sweep)
 			shift; [ ${#render[@]} -eq 0 ] || abortSingleRenderer "$0"; render=("${SWEEPS[@]}"); isCaptureStdout=t;;
 	--sweep-stderr)
 			shift; [ ${#render[@]} -eq 0 ] || abortSingleRenderer "$0"; render=("${SWEEPS[@]}");;
+	--inline-sweep-stderr)
+			shift; [ ${#render[@]} -eq 0 ] || abortSingleRenderer "$0"; render=("${SWEEPS[@]}"); isCaptureStdout=t; isInlineWithRender=t;;
 	--timespan|-t)	shift; timespan="$(timeToSeconds "$1")" || exit $?; shift;;
 	--initial-delay|-T)
 			shift; initialDelay="$(timeToSeconds "$1")" || exit $?; shift;;
@@ -411,6 +424,7 @@ STDIN_START=''
 STDIN_END=''
 
 teeStdoutCommand=; [ "$isCaptureStdout" ] && if [ ${#render[@]} -eq 0 ]; then teeStdoutCommand='tee -a /dev/stderr'; else teeStdoutCommand="tee >(sed --unbuffered 's/.*/${STDIN_START}&${STDIN_END}/' >> /dev/stderr)"; fi
+stdinLine=
 let renderCount=0
 unset previousLine
 unset status
@@ -424,7 +438,18 @@ do
 	    invokeTargetAndResetTimer "$netLine"
 	fi
     elif [ "${#render[@]}" -gt 0 ]; then
-	if [ "$isCaptureStdout" ]; then
+	if [ "$isInlineWithRender" ]; then
+	    stderrLine="${netLine//${STDIN_START}*${STDIN_END}/}"
+	    if [ "$stderrLine" != "$netLine" ]; then
+		stdinLine="${netLine#*${STDIN_START}}"
+		stdinLine="${stdinLine%%${STDIN_END}*}"
+	    fi
+	    if invokeTargetAndResetTimer "${stdinLine}${stdinLine:+ }${render[$renderCount]}"; then
+		let renderCount=$(((renderCount + 1) % ${#render[@]}))
+	    fi
+	    statusLine="$line"
+	    continue
+	elif [ "$isCaptureStdout" ]; then
 	    stderrLine="${netLine//${STDIN_START}*${STDIN_END}/}"
 	    if [ -n "$stderrLine" ]; then
 		printf '%s\n' "$stderrLine"
@@ -454,7 +479,7 @@ done < <(
 	    eval '"${commands[@]}"' ${teeStdoutCommand:+|}$teeStdoutCommand
 	fi 4>&1 1>&2 2>&4 4>&-
 	status=${PIPESTATUS[0]}
-	${teeStdoutCommand:+sleep 0}
+	${teeStdoutCommand:+sleep ${INVOCATIONNOTIFICATION_SYNC_DELAY:-0.01}}
 	exit $status
     )
     printf '%s%d\n' "$STATUSLINE_PREFIX" "$?"
