Reimplementation: Minor: Replace timeToSeconds() with delegation to durationToSeconds
Its implementation now supports the millisecond resolution that the --timespan and --initial-delay parameters allow.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/invocationNotification b/bin/invocationNotification
--- a/bin/invocationNotification
+++ b/bin/invocationNotification
@@ -40,7 +40,7 @@ printShortUsage()
     # skim the long one.
     local IFS='|'
     local extensionNameList="${extensions[*]##*/}"
-    printf 'Usage: %q %s\n' "$(basename "$1")" "-m|--message MESSAGE -o|--to overlay|title|command|notify${extensionNameList:+|}${extensionNameList} [--success SIGIL] [--fail SIGIL] [-C|--clear success|failure|all] [-i|--inline|--spinner|--sweep|--inline-stderr|--spinner-stderr|--sweep-stderr|--inline-spinner-stderr|--inline-sweep-stderr|--spinner-stderr-inline|--sweep-stderr-inline [--render-timer INTERVAL[SUFFIX]] [-t|--timespan TIMESPAN[SUFFIX]]] [-T|--initial-delay TIMESPAN[SUFFIX]] [--timer INTERVAL[SUFFIX]] -c|--command COMMANDLINE [...]|[--] SIMPLECOMMAND"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "-m|--message MESSAGE -o|--to overlay|title|command|notify${extensionNameList:+|}${extensionNameList} [--success SIGIL] [--fail SIGIL] [-C|--clear success|failure|all] [-i|--inline|--spinner|--sweep|--inline-stderr|--spinner-stderr|--sweep-stderr|--inline-spinner-stderr|--inline-sweep-stderr|--spinner-stderr-inline|--sweep-stderr-inline [--render-timer INTERVAL] [-t|--timespan TIMESPAN]] [-T|--initial-delay TIMESPAN] [--timer INTERVAL] -c|--command COMMANDLINE [...]|[--] SIMPLECOMMAND"
 }
 printUsage()
 {
@@ -73,6 +73,8 @@ HELPDESCRIPTION
     echo
     printShortUsage "$1"
     echo
+    local timespanFormat="$(DURATIONTOSECONDS_ACCEPT_FRACTIONAL=t durationToSeconds --get-short-usage format 2>/dev/null)"
+    local intervalFormat="$(durationToSeconds --get-short-usage format 2>/dev/null)"
     cat <<HELPTEXT
     --to|-o overlay	Report in the form of overlaid text, written via ANSI
 			escape sequences in the first line of the terminal.
@@ -145,21 +147,18 @@ HELPDESCRIPTION
 			before MESSAGE / the last line like --sweep-stderr.
 			Same as --inline-sweep-stderr but the sweeping control
 			comes first.
-    --timespan|-t TIMESPAN[SUFFIX]
+    --timespan|-t ${timespanFormat:-TIMESPAN}
 			Only append / spin / sweep a line every TIMESPAN instead
 			of every second. Use --timespan 0 to use every line.
-			SUFFIX may be 'ms' for milliseconds, 's' for seconds
-			(the default), 'm' for minutes, 'h' for hours or 'd' for
-			days.
-    --initial-delay|-T TIMESPAN[SUFFIX]
+    --initial-delay|-T ${timespanFormat:-TIMESPAN}
 			Wait for TIMESPAN before notifying with the message or
 			appending / spinning / sweeping based on a line. By
 			default, the first notification happens immediately.
-    --timer INTERVAL[SUFFIX]
+    --timer ${intervalFormat:-INTERVAL}
 			Append the COMMAND's total running time after MESSAGE
 			every INTERVAL. This provides some form of feedback if
 			COMMAND does not (or not often) provide output.
-    --render-timer INTERVAL[SUFFIX]
+    --render-timer ${intervalFormat:-INTERVAL}
 			Rotate the spinner / change the sweeping control every
 			INTERVAL. This provides some form of feedback if COMMAND
 			does not (or not often) provide output.
@@ -174,24 +173,6 @@ EXIT STATUS:
 Example:
 HELPTEXT
     printf '%q %s\n' "$(basename "$1")" "-t overlay -m 'Google ping time: ' --inline-stderr -c 'ping -c 10 www.google.com 2>&1 | stdbuf -oL grep --line-buffered -o time=.* >&2'"
-}
-
-timeToSeconds()
-{
-    case "$1" in
-	+([0-9])ms)	if [ "$3" ]; then
-			    echo >&2 "ERROR: Fractional seconds not allowed for ${2:-timespan}."; exit 2
-			else
-			    time="00${1%ms}"; time="0${time%???}.${time:$((${#time}-3))}"; time="${time/#+(0)/0}"
-			fi
-			;;
-	+([0-9])?(s))   time="${1%s}";;
-	+([0-9])m)	time=$((${1%m} * 60));;
-	+([0-9])h)	time=$((${1%h} * 3600));;
-	+([0-9])d)	time=$((${1%d} * 86400));;
-	*)		printf >&2 "ERROR: Illegal ${2:-timespan}: %s\\n" "$1"; exit 2;;
-    esac
-    printf %s "$time"
 }
 
 singleTargetCheck()
@@ -335,11 +316,11 @@ do
 			shift; [ ${#render[@]} -eq 0 ] || abortSingleRenderer "$0"; render=("${sweeps[@]}"); isCaptureStdout=t; isInlineWithRender=t;;
 	--sweep-stderr-inline)
 			shift; [ ${#render[@]} -eq 0 ] || abortSingleRenderer "$0"; render=("${sweeps[@]}"); isCaptureStdout=t; isInlineWithRender=t; isRenderBeforeInline=t;;
-	--timespan|-t)	shift; timespan="$(timeToSeconds "$1")" || exit $?; shift;;
+	--timespan|-t)	shift; timespan=$(DURATIONTOSECONDS_ACCEPT_FRACTIONAL=t durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
 	--initial-delay|-T)
-			shift; initialDelay="$(timeToSeconds "$1")" || exit $?; shift;;
-	--timer)	shift; reader=timeoutReader; timer="$(timeToSeconds "$1" interval t)" || exit $?; shift; SECONDS=0; isTimer=t;;
-	--render-timer)	shift; reader=timeoutReader; timer="$(timeToSeconds "$1" interval t)" || exit $?; shift; SECONDS=0; isRenderTimer=t;;
+			shift; initialDelay=$(DURATIONTOSECONDS_ACCEPT_FRACTIONAL=t durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
+	--timer)	shift; reader=timeoutReader; timer="$(durationToSeconds -- "${1:?}")" || { printf >&2 'ERROR: Illegal INTERVAL: %s\n' "$1"; exit 2; }; shift; SECONDS=0; isTimer=t;;
+	--render-timer)	shift; reader=timeoutReader; timer="$(durationToSeconds -- "${1:?}")" || { printf >&2 'ERROR: Illegal INTERVAL: %s\n' "$1"; exit 2; }; shift; SECONDS=0; isRenderTimer=t;;
 	--command|-c)	shift; commands+="${commands:+ $INVOCATIONNOTIFICATION_COMMAND_JOINER }$1"; shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
