invocationNotificationToAppendix: Robustness: Minor: Add check for titleupdate

diff --git a/bin/invocationNotificationToAppendix b/bin/invocationNotificationToAppendix
--- a/bin/invocationNotificationToAppendix
+++ b/bin/invocationNotificationToAppendix
@@ -15,6 +15,11 @@ case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
 
+if ! type -t titleupdate >/dev/null; then
+    echo >&2 'ERROR: titleupdate is not available.'
+    exit 3
+fi
+
 INVOCATIONNOTIFICATION_POST_COMMANDLINE="titleupdate --id invocationNotificationToAppendix --clear 2>/dev/null" \
 INVOCATIONNOTIFICATION_COMMANDLINE="titleupdate --id invocationNotificationToAppendix {}" \
 exec invocationNotification --to command "$@"
