WIP: Copy command-line argument parsing and basic infrastructure for timer from invocationMessage

diff --git a/bin/invocationNotification b/bin/invocationNotification
--- a/bin/invocationNotification
+++ b/bin/invocationNotification
@@ -5,6 +5,12 @@ shopt -qs extglob
 messageMarker="$INVOCATIONNOTIFICATION_MESSAGE_MARKER"; unset INVOCATIONNOTIFICATION_MESSAGE_MARKER
 : ${INVOCATIONNOTIFICATION_SUCCESS_DISPLAY_DELAY=0.3}
 : ${INVOCATIONNOTIFICATION_FAIL_DISPLAY_DELAY=1}
+: ${INVOCATIONNOTIFICATION_TIMER_INLINE_PREFIX=(}
+: ${INVOCATIONNOTIFICATION_TIMER_INLINE_SUFFIX=) }
+: ${INVOCATIONNOTIFICATION_TIMER_RENDER_PREFIX=(}
+: ${INVOCATIONNOTIFICATION_TIMER_RENDER_SUFFIX=) }
+: ${INVOCATIONNOTIFICATION_TIMER_SIGIL_PREFIX= (}
+: ${INVOCATIONNOTIFICATION_TIMER_SIGIL_SUFFIX=)}
 typeset -a SPINNER=(/ - \\ \|)
 typeset -a SWEEPS=('[*   ]' '[-*  ]' '[ -* ]' '[  -*]' '[   *]' '[  *-]' '[ *- ]' '[*-  ]')
 
@@ -12,7 +18,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-m|--message MESSAGE -o|--to overlay|title|command|notify [--success SIGIL] [--fail SIGIL] [-C|--clear success|failure|all] [-i|--inline|--spinner|--sweep|--inline-stderr|--spinner-stderr|--sweep-stderr|--inline-spinner-stderr|--inline-sweep-stderr|--spinner-stderr-inline|--sweep-stderr-inline [-t|--timespan TIMESPAN[SUFFIX]]] [-T|--initial-delay TIMESPAN[SUFFIX]] -c|--command COMMANDLINE [...]|[--] SIMPLECOMMAND'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-m|--message MESSAGE -o|--to overlay|title|command|notify [--success SIGIL] [--fail SIGIL] [-C|--clear success|failure|all] [-i|--inline|--spinner|--sweep|--inline-stderr|--spinner-stderr|--sweep-stderr|--inline-spinner-stderr|--inline-sweep-stderr|--spinner-stderr-inline|--sweep-stderr-inline [--render-timer INTERVAL[SUFFIX]] [-t|--timespan TIMESPAN[SUFFIX]]] [-T|--initial-delay TIMESPAN[SUFFIX]] [--timer INTERVAL[SUFFIX]] -c|--command COMMANDLINE [...]|[--] SIMPLECOMMAND'
 }
 printUsage()
 {
@@ -118,6 +124,14 @@ HELPDESCRIPTION
 			Wait for TIMESPAN before notifying with the message or
 			appending / spinning / sweeping based on a line. By
 			default, the first notification happens immediately.
+    --timer INTERVAL[SUFFIX]
+			Append the COMMAND's total running time after MESSAGE
+			every INTERVAL. This provides some form of feedback if
+			COMMAND does not (or not often) provide output.
+    --render-timer INTERVAL[SUFFIX]
+			Rotate the spinner / change the sweeping control every
+			INTERVAL. This provides some form of feedback if COMMAND
+			does not (or not often) provide output.
     --command|-c CMD	Execute the passed command line. When this is a simple
 			command, it can also be passed as such.
 EXIT STATUS:
@@ -134,12 +148,17 @@ HELPTEXT
 timeToSeconds()
 {
     case "$1" in
-	+([0-9])ms)	time="00${1%ms}"; time="0${time%???}.${time:$((${#time}-3))}"; time="${time/#+(0)/0}";;
+	+([0-9])ms)	if [ "$3" ]; then
+			    echo >&2 "ERROR: Fractional seconds not allowed for ${2:-timespan}."; exit 2
+			else
+			    time="00${1%ms}"; time="0${time%???}.${time:$((${#time}-3))}"; time="${time/#+(0)/0}"
+			fi
+			;;
 	+([0-9])?(s))   time="${1%s}";;
 	+([0-9])m)	time=$((${1%m} * 60));;
 	+([0-9])h)	time=$((${1%h} * 3600));;
 	+([0-9])d)	time=$((${1%d} * 86400));;
-	*)		printf >&2 "ERROR: Illegal timespan: %s\\n" "$1"; exit 2;;
+	*)		printf >&2 "ERROR: Illegal ${2:-timespan}: %s\\n" "$1"; exit 2;;
     esac
     printf %s "$time"
 }
@@ -231,6 +250,10 @@ isRenderBeforeInline=
 typeset -a render=()
 unset timespan
 initialDelay=0
+reader=defaultReader
+timer=
+isTimer=
+isRenderTimer=
 isNeedEval=
 typeset -a commands=()
 while [ $# -ne 0 ]
@@ -271,6 +294,8 @@ do
 	--timespan|-t)	shift; timespan="$(timeToSeconds "$1")" || exit $?; shift;;
 	--initial-delay|-T)
 			shift; initialDelay="$(timeToSeconds "$1")" || exit $?; shift;;
+	--timer)	shift; reader=timeoutReader; timer="$(timeToSeconds "$1" interval t)" || exit $?; shift; SECONDS=0; isTimer=t;;
+	--render-timer)	shift; reader=timeoutReader; timer="$(timeToSeconds "$1" interval t)" || exit $?; shift; SECONDS=0; isRenderTimer=t;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
@@ -308,6 +333,11 @@ elif [ -n "${timespan+t}" ] && [ ! "$isInline" ] && [ ${#render[@]} -eq 0 ]; the
     echo
     printShortUsage "$0"
     exit 2
+elif [ "$isRenderTimer" ] && [ ${#render[@]} -eq 0 ]; then
+    echo 'ERROR: --render-timer can only be used in combination with --spinner[-stderr] or --sweep[-stderr].'
+    echo
+    printShortUsage "$0"
+    exit 2
 elif [ ${#commands[@]} -eq 0 ]; then
     echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
     exit 2
@@ -334,9 +364,23 @@ elif [ "$target" = 'notifyTarget' ]; then
     # Reuse the commandTarget for this specialization.
     INVOCATIONNOTIFICATION_COMMANDLINE="$INVOCATIONNOTIFICATION_NOTIFY_COMMANDLINE"
 fi >&2
-: ${timespan:=1}
 
-case "${timespan}:${initialDelay}" in
+: ${timespan:=1}
+# If the timer is used, reserve use of SECONDS for that (as we can easily (but a
+# bit more slowly) use external date for the timespan and initial delay), as
+# timing interval likely will fire more often than the (likely infrequent)
+# output.
+case "${timespan}:${initialDelay}${timer:+.}" in
+    0:0?(.))
+	resetTime()
+	{
+	    :
+	}
+	isExpired()
+	{
+	    :
+	}
+	;;
     *.*)
 	: ${DATE:=date}
 
@@ -367,16 +411,6 @@ case "${timespan}:${initialDelay}" in
 		;;
 	esac
 	;;
-    0:0)
-	resetTime()
-	{
-	    :
-	}
-	isExpired()
-	{
-	    :
-	}
-	;;
     *)
 	resetTime()
 	{
@@ -392,6 +426,42 @@ case "${timespan}:${initialDelay}" in
 	}
 	;;
 esac
+
+line=
+duration=0
+lastDuration=0
+defaultReader()
+{
+    IFS=$'\n' read -r line
+}
+heldChars=''
+timeoutReader()
+{
+    local char
+    while :
+    do
+	if IFS=$'\n' read -t 2 -n 1 -r char; then
+	    if [ -z "$char" ]; then
+		line="${heldChars}"
+		heldChars=''
+		return 0
+	    else
+		heldChars="${heldChars}$char"
+		continue
+	    fi
+	elif [ $? -gt 128 ]; then
+	    duration=$SECONDS
+	    return 0
+	elif [ -n "$heldChars" ]; then
+	    line="$heldChars"
+	    heldChars=''
+	    return 0
+	else
+	    line=''
+	    return 1
+	fi
+    done
+}
 
 isTerminalOk=t
 printfToTerminal()
