{invocation,progress}NotificationToAddendum: Robustness: Also check for $TERMID before proceeding
When running without a terminal (cron job, Conky), no notification is possible. Let's detect that early and avoid the invocation chain completely.

diff --git a/bin/progressNotificationToAddendum b/bin/progressNotificationToAddendum
--- a/bin/progressNotificationToAddendum
+++ b/bin/progressNotificationToAddendum
@@ -18,6 +18,9 @@ esac
 if ! type -t titleupdate >/dev/null; then
     echo >&2 'ERROR: titleupdate is not available.'
     exit 3
+elif [ -z "$TERMID" ]; then
+    echo >&2 'ERROR: Cannot notify via titleupdate; TERMID not defined.'
+    exit 3
 fi
 
 PROGRESSNOTIFICATION_POST_COMMANDLINE="titleupdate --id progressNotificationToAddendum --clear 2>/dev/null" \
