Fix adjustment implementation and add test coverage for ADJUSTMENT

diff --git a/bin/progressNotification b/bin/progressNotification
--- a/bin/progressNotification
+++ b/bin/progressNotification
@@ -87,7 +87,7 @@ timeToSeconds()
 	+([0-9])m)	time=$((${1%m} * 60));;
 	+([0-9])h)	time=$((${1%h} * 3600));;
 	+([0-9])d)	time=$((${1%d} * 86400));;
-	*)		printf >&2 'ERROR: Illegal timespan: %s\n' "$1"; exit 2;;
+	*)		printf >&2 "ERROR: Illegal ${2:-timespan}: %s\\n" "$1"; exit 2;;
     esac
     printf %s "$time"
 }
@@ -99,9 +99,11 @@ timeWithAdjustmentToSeconds()
 	printf >&2 'ERROR: Empty timespan: %s\n' "$time"; exit 2;
     fi
     case "$adjustment" in
-	'')			;;
-	[+-]+([0-9])?([smhd%]))	;;
-	*)  printf >&2 'ERROR: Illegal adjustment: %s\n' "$adjustment"; exit 2;;
+	'')		    ;;
+	[+-]+([0-9])?(%))   ;;
+	++([0-9])[smhd])    adjustment="+$(timeToSeconds "${adjustment#+}" adjustment)" || return $?;;
+	-+([0-9])[smhd])    adjustment="-$(timeToSeconds "${adjustment#-}" adjustment)" || return $?;;
+	*)		    printf >&2 'ERROR: Illegal adjustment: %s\n' "$adjustment"; exit 2;;
     esac
     time="$(timeToSeconds "$time" "$2")" || exit $?
     printf '%s\t%s\n' "$time" "$adjustment"
@@ -137,8 +139,6 @@ adjust()
     esac
 
     [ $newValue -lt 0 ] && newValue=0
-    # Use this instead if no delay at all does not make sense.
-    #[ $newValue -le 0 ] && newValue=1
     eval "$var=\$newValue"
 }
 
@@ -271,7 +271,7 @@ elif [ "$target" = 'notifyTarget' ]; then
     PROGRESSNOTIFICATION_COMMANDLINE="$PROGRESSNOTIFICATION_NOTIFY_COMMANDLINE"
 fi >&2
 
-case "${timespan}${initialDelay}" in
+case "${timespan}${initialDelay}${DATE:+.}" in	# Testing: Switch to fractional time when DATE is defined because the testing hook is only available there.
     0:0)
 	resetTime()
 	{
