Robustness: Ensure numeric MAX_COUNT

diff --git a/bin/progressNotification b/bin/progressNotification
--- a/bin/progressNotification
+++ b/bin/progressNotification
@@ -230,7 +230,14 @@ do
 	--to|-o)	shift; singleTargetCheck "$0"; target="${1}Target"; if ! type -t "$target" >/dev/null; then printf 'ERROR: No such target: %s\n' "$1"; echo; printUsage "$0"; exit 2; fi >&2; shift;;
 	--count|-n)	shift; countWhat="$1"; shift;;
 	--percentage|-p)
-			shift; endCount="$1"; shift;;
+			shift
+			if ! [[ "$1" =~ ^[0-9]+$ ]]; then
+			    echo >&2 'ERROR: Need numeric MAX_COUNT for --percentage.'
+			    exit 2
+			fi
+			endCount="$1"
+			shift
+			;;
 	--timespan|-t)	shift; < <(timeWithAdjustmentToSeconds "$1") IFS=$'\t' read -r timespan timespanAdjustment || exit 2; shift;;
 	--initial-delay|-T)
 			shift; initialDelay="$(timeToSeconds "$1")" || exit $?; shift;;
