progressNotification: CHG: Implement extension point within the command and use that for the addendum type
It's nicer to just invoke "progressNotification --to addendum" instead of having to use a separate "progressNotificationToAddendum" command. For clients, the sink now is completely transparent, regardless of whether it's built-in or an extension.

diff --git a/bin/progressNotification b/bin/progressNotification
--- a/bin/progressNotification
+++ b/bin/progressNotification
@@ -1,14 +1,28 @@
 #!/bin/bash
-shopt -qs extglob
+shopt -qs extglob nullglob
 
 : ${PROGRESSNOTIFICATION_REPORT_MARKER='{}'}
 reportMarker="$PROGRESSNOTIFICATION_REPORT_MARKER"; unset PROGRESSNOTIFICATION_REPORT_MARKER
+
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly extensionsDir="${projectDir}/lib/$(basename -- "${BASH_SOURCE[0]}")/extensions"
+typeset -a extensions=()
+typeset -A extensionNames=()
+for element in "${extensionsDir}"/*
+do
+    extensions+=("$element")
+    extensionNames["${element##*/}"]="$element"
+done
 
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-o|--to overlay|title|command|notify [-t|--timespan TIMESPAN[SUFFIX][ADJUSTMENT]] [-T|--initial-delay TIMESPAN[SUFFIX]] [-c|--append-count|-C|--prepend-count WHAT [--count-to END-COUNT]] [-p|--append-percentage|-P|--prepend-percentage END-COUNT] [-?|-h|--help]'
+    local IFS='|'
+    local extensionList="${!extensionNames[*]}"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "-o|--to overlay|title|command|notify${extensionList:+|}${extensionList} [-t|--timespan TIMESPAN[SUFFIX][ADJUSTMENT]] [-T|--initial-delay TIMESPAN[SUFFIX]] [-c|--append-count|-C|--prepend-count WHAT [--count-to END-COUNT]] [-p|--append-percentage|-P|--prepend-percentage END-COUNT] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -19,6 +33,12 @@ printUsage()
 }
 printLongUsage()
 {
+    local IFS=$'\n'
+    local extension; for extension in "${extensions[@]}"
+    do
+	source "$extension" 2>/dev/null
+    done
+
     # This is the long "man page" when launched with the help argument.
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
@@ -40,7 +60,8 @@ HELPDESCRIPTION
 			nothing at all if PROGRESSNOTIFICATION_CLEAR_COMMANDLINE
 			is defined but empty.
     --to|-o notify	Update via notify-send to the system's notification
-			system.
+			system.${extensionsLongUsages[*]:+
+}${extensionsLongUsages[*]}
     --timespan|-t TIMESPAN[SUFFIX][ADJUSTMENT]
 			Update every TIMESPAN instead of every second.
 			SUFFIX may be 'ms' for milliseconds, 's' for seconds
@@ -234,7 +255,21 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--to|-o)	shift; singleTargetCheck "$0"; target="${1}Target"; if ! type -t "$target" >/dev/null; then printf 'ERROR: No such target: %s\n' "$1"; echo; printUsage "$0"; exit 2; fi >&2; shift;;
+	--to|-o)	shift
+			singleTargetCheck "$0"
+			target="${1}Target"
+			if ! type -t "$target" >/dev/null; then
+			    if extension="${extensionNames["$1"]}" && [ -n "$extension" ]; then
+				source "$extension" || exit $?
+			    else
+				printf 'ERROR: No such target: %s\n' "$1"
+				echo
+				printUsage "$0"
+				exit 2
+			    fi
+			fi >&2
+			shift
+			;;
 	--prepend-count|-C)
 			isCountPrepend=t;&
 	--append-count|-c)
